export const KAZAKHSTAN_CITY_SCHOOLS = {
  Almaty: [
    'NIS PhM Almaty',
    'BIL Almaty',
    'School-Gymnasium No. 15',
    'Lyceum No. 134',
    'Private School Almaty',
  ],
  Astana: [
    'Astana English School',
    'Astana Garden School',
    'Al-Farabi International School',
    'Bibigul Tulegenova Creative School',
    'Bilim-Innovation Lyceum (Boys)',
    'Bilim-Innovation Lyceum (Girls)',
    'BINOM School Akhmet Baitursynov',
    'BINOM School Alikhan Bokeikhan',
    'BINOM School Kanysh Satpayev',
    'BINOM School Saryarka',
    'BINOM School Turan',
    'BINOM School Uly Dala',
    'Capital School',
    'Fizmat Astana',
    'Flamingo School',
    'Haileybury Astana',
    'Harmony School',
    'International College of Continuous Education (ICCE)',
    'International Steppe School',
    'Miras International School',
    'Nazarbayev Intellectual School (IB)',
    'Nazarbayev Intellectual School (Physics and Math)',
    'Neotech Digital School',
    'Nova School',
    'Nurorda International School',
    'Qadam School',
    'QSI International School of Astana',
    'Quantum STEM School',
    'Riviera International School',
    'SEED School',
    'Skillset School',
    'Spectrum International School',
    'Zerdeli International School',
    'School No. 1',
    'School No. 2',
    'School No. 3',
    'School No. 4 (Zhambyl Zhabayev)',
    'School No. 5',
    'School No. 6',
    'School No. 7',
    'School No. 8',
    'School No. 9 (Zerde)',
    'School No. 10 (Zhumabek Tashenov)',
    'School No. 11 (Uzbekali Zhanibekov)',
    'School No. 13',
    'School No. 14',
    'School No. 15',
    'School No. 16 (Tolegen Aibergenov)',
    'School No. 17',
    'School No. 18',
    'School No. 19',
    'School No. 20',
    'School No. 21',
    'School No. 22 (Alem)',
    'School No. 24',
    'School No. 25',
    'School No. 26',
    'School No. 27',
    'School No. 28',
    'School No. 29',
    'School No. 30',
    'School No. 31',
    'School No. 32',
    'School No. 34',
    'School No. 35',
    'School No. 36',
    'School No. 37 (Syrbay Maulenov)',
    'School No. 38',
    'School No. 40',
    'School No. 41',
    'School No. 42',
    'School No. 43',
    'School No. 44',
    'School No. 45',
    'School No. 46',
    'School No. 47',
    'School No. 48',
    'School No. 49 (Koshke Kemengeruly)',
    'School No. 50',
    'School No. 51',
    'School No. 52',
    'School No. 53',
    'School No. 54',
    'School No. 55',
    'School No. 56 (Shakarim)',
    'School No. 57',
    'School No. 58',
    'School No. 59',
    'School No. 60',
    'School No. 61',
    'School No. 62',
    'School No. 63',
    'School No. 64',
    'School No. 65',
    'School No. 66 (Dinmukhamed Kunayev)',
    'School No. 67 (Ilyas Yesenberlin)',
    'School No. 68',
    'School No. 69',
    'School No. 70',
    'School No. 71',
    'School No. 72',
    'School No. 73',
    'School No. 74',
    'School No. 75',
    'School No. 76 (Alikhan Bokeikhan)',
    'School No. 77',
    'School No. 78',
    'School No. 79',
    'School No. 80 (Saken Seifullin)',
    'School No. 82 (Daryn)',
    'School No. 83 (Ibrai Altynsarin)',
    'School No. 84 (Sheikh Khalifa bin Zayed Al Nahyan)',
    'School No. 85 (Sheikh Tamim bin Hamad Al-Thani)',
    'School No. 86 (Mukhtar Auezov)',
    'School No. 87 (Abay Kunanbayev)',
    'School No. 88',
    'School No. 89',
    'School No. 90',
    'School No. 91',
    'School No. 92',
    'School No. 93',
    'School No. 94',
    'School No. 95',
    'School No. 96',
    'School No. 97',
    'School No. 98',
    'School No. 99',
    'School No. 100',
    'School No. 101',
    'School No. 102',
    'School No. 103',
    'School No. 104',
    'School No. 105',
    'School No. 106',
    'School No. 107',
    'School No. 108',
    'School No. 109',
    'School No. 110',
    'School No. 111',
    'School No. 112',
  ],
  Shymkent: [
    'NIS PhM Shymkent',
    'BIL Shymkent',
    'School-Gymnasium No. 8',
    'School-Lyceum No. 1',
    'Private School Shymkent',
  ],
  Karaganda: [
    'NIS PhM Karaganda',
    'BIL Karaganda',
    'Gymnasium No. 38',
    'School-Lyceum No. 57',
    'Private School Karaganda',
  ],
  Aktobe: [
    'NIS Aktobe',
    'BIL Aktobe',
    'School-Gymnasium No. 21',
    'Lyceum No. 24',
    'Private School Aktobe',
  ],
  Atyrau: [
    'NIS Atyrau',
    'BIL Atyrau',
    'School No. 17',
    'Lyceum No. 35',
    'Private School Atyrau',
  ],
  Kostanay: [
    'NIS Kostanay',
    'BIL Kostanay',
    'Gymnasium No. 18',
    'School-Lyceum No. 1 Kostanay',
    'Private School Kostanay',
  ],
  Kokshetau: [
    'NIS Kokshetau',
    'BIL Kokshetau',
    'School-Gymnasium No. 13',
    'Lyceum No. 6',
    'Private School Kokshetau',
  ],
  Pavlodar: [
    'NIS Pavlodar',
    'BIL Pavlodar',
    'School No. 39',
    'Gymnasium No. 10',
    'Private School Pavlodar',
  ],
  Semey: [
    'NIS Semey',
    'BIL Semey',
    'School-Lyceum No. 44',
    'Gymnasium No. 37',
    'Private School Semey',
  ],
  Taraz: [
    'NIS Taraz',
    'BIL Taraz',
    'School-Gymnasium No. 7',
    'Lyceum No. 3 Taraz',
    'Private School Taraz',
  ],
  'Ust-Kamenogorsk': [
    'NIS Ust-Kamenogorsk',
    'BIL Ust-Kamenogorsk',
    'School-Lyceum No. 43',
    'Gymnasium No. 38',
    'Private School Ust-Kamenogorsk',
  ],
} as const;

export type KazakhstanCity = keyof typeof KAZAKHSTAN_CITY_SCHOOLS;

export const KAZAKHSTAN_CITIES = Object.keys(KAZAKHSTAN_CITY_SCHOOLS) as KazakhstanCity[];

export function getSchoolsByCity(city: string) {
  if (!city) return [];
  return KAZAKHSTAN_CITY_SCHOOLS[city as KazakhstanCity] ?? [];
}